name: Add lint reviews to PRs

on:
  pull_request:
    branches:
      - main

jobs:
  lint-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Try to write event file
        run: |
          echo "Hello" > "$GITHUB_EVENT_PATH"
